### ISSUE TITLE
[Feature Request] Website i18n

### ISSUE THREAD

**Issue by poikcue** [PaperMC/face-lift#33]
Will the new website support i18n? For people whose native language is not English (or who don't speak English very well) it can be effective to help them use PaperMC's software.

**Comment by electronicboy** [comment]
Unlikely, web browsers automatic translation stuff is stupidly accessible these days, the burden of work to support localisation is excessive, especially for what is essentially a smallish gateway

**Comment by poikcue** [comment]
> Unlikely, web browsers automatic translation stuff is stupidly accessible these days, the burden of work to support localisation is excessive, especially for what is essentially a smallish gateway

Thank you for your prompt reply!
I think PaperMC's official website deserves to be localized. Here is my opinion.
According to velocity's crowdin page and the [lukperms](luckperms.net) website, there are many people willing to translate. And it seems that the new PaperMC website is not ready for official use yet, so there is plenty of time for localization. Also, PaperMC's official website doesn't have a huge amount of text to translate, even less than the amount of work required for plugin localization. 
I am not a developer, so I am not sure if i18n is difficult to develop, please forgive me.
If possible, I can translate into Simplified Chinese.
